repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
      args: ["--py39-plus"]

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [pep8-naming]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
