repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.9.2
    hooks:
    - id: isort
      args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    - id: black

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.21.0
    hooks:
    - id: pyupgrade
      args: ["--py39-plus"]

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
