name: CI

on:
  push:
  workflow_dispatch:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool: [
          'isort',
          'black',
          'pyupgrade',
          'flake8',
          'trailing-whitespace',
          'end-of-file-fixer',
          'fix-byte-order-marker']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
          pre-commit install
      - name: Run ${{ matrix.tool }}
        run: |
          pre-commit run ${{ matrix.tool }} --all-files
