name: Ambient Sound Processing

on:
  # To run manually
  workflow_dispatch:
  schedule:
    - cron: '2 * * * *'
    
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.9.18'
        cache: 'pip'
        cache-dependency-path: requirements_noise.txt

    - name: Install Python dependencies
      run: |
        pip install -r requirements_noise.txt

 
    - name: Install ffmpeg
      run: |
       sudo apt-get update
       sudo apt-get install ffmpeg
    
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: ffmpeg

    - name: Create plots
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python noise_processing.py

    - name: Upload to GitHub repo
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Commit to Github
          commit_user_name: Action Bot
          commit_user_email: bot@example.com 
          commit_author: Author <actions@github.com>
          file_pattern: 'img/*.png'

    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ambient_sound_plots
        path: img/*.png

   # - name: Upload to Google Drive
   #   uses: AnimMouse/setup-rclone@v1
   #   with:
   #     rclone_config: ${{secrets.RCLONE_CONFIG}}
   #   
   # - run: |
   #     rclone copy ambient_sound_analysis/img/broadband.png mydrive:rclone_uploads/
